name: Deploy AWS Lambda .NET

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Restore dependencies
        run: dotnet restore ./src/MyLambdaFunctionDemo/MyLambdaFunctionDemo.csproj

      - name: Build project
        run: dotnet build ./src/MyLambdaFunctionDemo/MyLambdaFunctionDemo.csproj --configuration Release

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          dotnet lambda deploy-function MyLambdaFunctionDemo \
            --project-location ./src/MyLambdaFunctionDemo \
            --region $AWS_REGION \
            --function-role arn:aws:iam::570829448606:role/Aws_Test_Profile_Role \
      - name: Install AWS SAM CLI
        run: |
            pip install aws-sam-cli

      - name:  Install dependencies
        run: dotnet restore

      - name: Build Lambda
        run: sam build

      - name: Deploy Lambda
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name my-scheduled-lambda \
          --capabilities CAPABILITY_IAM \
          --region us-east-1 \        
            
